### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by liraku** [leathalman/Jotify#1]

**Comment by liraku** [comment]
can not run successful

**Comment by leathalman** [comment]
Hey thank you for checking out the repo. Could you possibly provide some details as to why it is not running, and the error messages you are getting?

**Comment by liraku** [comment]
![0CB21BF2-8143-4ADF-B4EC-EA1EA4678E48](https://user-images.githubusercontent.com/13781077/61344361-983fa200-a883-11e9-9761-49c4b216ed0b.png)

**Comment by leathalman** [comment]
You need to be using the Xcode 11 Beta as well as running iOS 13 on any devices you plan to run this on. I should have added this information to the readme, my bad!

**Comment by liraku** [comment]
thanks
